### ISSUE TITLE
NullPointerException in jasmin.Main.<clinit>

### ISSUE THREAD

**Issue by Aztorius** [Sable/jasmin#14]
Hi,

Tested with OpenJDK 8 and the Soot package 3.3.0 and 3.2.0 available on maven repositories.

When I was calling the flush() method of JasminOutputStream in Soot it throws some Exceptions.
`java.lang.ExceptionInInitializerError
        at soot.util.JasminOutputStream.flush(JasminOutputStream.java)
`

I found that it was in fact an issue in the `jasmin.Main.<clinit>` initializer (at the static level).
When looking at the code I think there can be an issue with this simple line :  
`public final static String version = Main.class.getPackage().getImplementationVersion() == null ? "trunk" : Main.class.getPackage().getImplementationVersion();`.

[src/jasmin/Main.java#L64](https://github.com/Sable/jasmin/blob/a19856058e91c6b9f1b38a35bf9d08d791928eb7/src/jasmin/Main.java#L64)

In fact according to the Java 8 spec [getPackage() can return null in some specific cases](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getPackage--). That explains why i get this NullPointerException at the loading phase of jasmin.Main.

A simple fix is to check if getPackage() is null before using it.

Also note that this behaviour will not happen on Java 9+, but I don't think this is relevant for now.

**Comment by mbenz89** [comment]
Hi William.

Thanks for reporting! Would you be able to propose a pull request for the fix?
