### ISSUE TITLE
Please upload jasmin to Maven Central

### ISSUE THREAD

**Issue by ebourg** [Sable/jasmin#5]
Hi,

I'd like to integrate Jasmin in a Maven project but the jar isn't available in the Maven central repository. Could you please upload it there?

Thank you

**Comment by ebourg** [comment]
I just noticed that jasmin was actually embedded in soot available from the conjars repository (http://conjars.org/repo/soot/soot/). An independent jasmin artifact in Maven central would still be useful though.

**Comment by mbenz89** [comment]
jasmin is available on Maven central by now.

**Comment by ebourg** [comment]
Thank you!
